# Generated by Django 5.0.1 on 2024-01-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='lab_hours',
            new_name='laboratory_hours',
        ),
    ]
